### Loading Library

In [1]:
import numpy as np

### 1. Creating numpy array

In [25]:
# a) array from 1D list

list1 = [2, 4, 6 ,8, 10]
arr1 = np.array (list1)

In [26]:
print (arr1)

[ 2  4  6  8 10]


In [27]:
type(arr1)

numpy.ndarray

Arrays are different from List. One can apply vectorised operation on arrays which is not possible in case of Python list.

In [28]:
list1 + 1

TypeError: can only concatenate list (not "int") to list

In [29]:
arr1 + 1

array([ 3,  5,  7,  9, 11])

In [30]:
# b) array from 2D list

list2 = [[9, 0, 4, 6], 
         [4 ,6, 2, 1]]
arr2 = np.array (list2)

In [31]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [32]:
# c) float array

arr2 = np.array(list2, dtype = 'float')

In [33]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [34]:
# d) converting array type

arr3 = arr2.astype('int')
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [35]:
# d) Boolean array

arr4 = np.array(list2, dtype = 'bool')
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
# e) Object array

arr5 = np.array([2, 5, 'y', 2], dtype = 'object')
arr5

array([2, 5, 'y', 2], dtype=object)

In [38]:
# f) Converting array to list

list3 = arr5.tolist()
list3

[2, 5, 'y', 2]

### 2. Array Dimensions

In [39]:
arr2.shape

(2, 4)

In [40]:
arr2.size

8

In [41]:
arr2.dtype

dtype('float64')

In [43]:
arr2.ndim

2

### 3. Reversing rows and columns

In [45]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [44]:
# reversing rows and columns

arr2[::-1, ::-1]

array([[1., 2., 6., 4.],
       [6., 4., 0., 9.]])

In [46]:
# reversing rows

arr2[::-1, ]

array([[4., 6., 2., 1.],
       [9., 0., 4., 6.]])

### 4. Specific element extraction

In [49]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [57]:
# ROW 1

arr2[:1, :]

array([[9., 0., 4., 6.]])

In [58]:
# Rows 

arr2[:2, ]

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [59]:
# Columns

arr2[:, -1] 

array([6., 1.])

In [62]:
arr2[:, 1: 3] 

array([[0., 4.],
       [6., 2.]])

### 5. Basic Statistics


In [63]:
arr2.min()

0.0

In [64]:
arr2.max()

9.0

In [65]:
arr2.sum()

32.0

In [66]:
arr2.mean()

4.0

In [69]:
np.median(arr2)

4.0

In [70]:
np.average(arr2)

4.0

In [72]:
np.var(arr2)

7.75

### 6. Reshaping and Flattening

In [73]:
arr2.shape

(2, 4)

In [74]:
arr2.reshape(4, 2)

array([[9., 0.],
       [4., 6.],
       [4., 6.],
       [2., 1.]])

In [76]:
f1 = arr2.flatten()
f1

array([9., 0., 4., 6., 4., 6., 2., 1.])

### 7. Creating Random arrays and sequences

In [80]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [84]:
np.arange(10, 0)

array([], dtype=int32)

In [85]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [90]:
np.linspace(start=1, stop = 10, num = 3)

array([ 1. ,  5.5, 10. ])

In [91]:
np.linspace(start=1, stop = 10, num = 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [93]:
np.linspace(start=1, stop = 10, num = 4)

array([ 1.,  4.,  7., 10.])

In [95]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [98]:
np.zeros([2, 3, 4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 8. Unique items and count

In [99]:
arr = [[1, 4, 5, 2 ,2, 5], 
       [4, 4, 1, 7, 4, 5]]

In [100]:
arr

[[1, 4, 5, 2, 2, 5], [4, 4, 1, 7, 4, 5]]

In [107]:
unique_val, count = np.unique(arr, return_counts = True)

In [108]:
unique_val

array([1, 2, 4, 5, 7])

In [109]:
count

array([2, 2, 4, 3, 1], dtype=int64)